quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
    jdbc:
      url: ${DB_URL:}
      statement-batch-size: 50
      max-lifetime: 1800s

  hibernate-orm:
    database:
      generation: none
    log:
      sql: true
      format-sql: true

  smallrye-jwt:
    enabled: true

technosou:
  admin:
    token: ${ADMIN_TOKEN:}
mp:
  jwt:
    verify:
      publickey:
        algorithm: ES256
        location: ${SUPABASE_LOCATION:}
      issuer: ${SUPABASE_ISSUER:}